<!-- Template JS Files -->
<script src="{{ asset ('js/jquery-3.5.0.min.js') }}"></script>
<script src="{{ asset ('js/styleswitcher.js') }}"></script>
<script src="{{ asset ('js/preloader.min.js') }}"></script>
<script src="{{ asset ('js/fm.revealator.jquery.min.js') }}"></script>
<script src="{{ asset ('js/imagesloaded.pkgd.min.js') }}"></script>
<script src="{{ asset ('js/masonry.pkgd.min.js') }}"></script>
<script src="{{ asset ('js/classie.js') }}"></script>
<script src="{{ asset ('js/cbpGridGallery.js') }}"></script>
<script src="{{ asset ('js/jquery.hoverdir.js') }}"></script>
<script src="{{ asset ('js/popper.min.js') }}"></script>
<script src="{{ asset ('js/bootstrap.js') }}"></script>
<script src="{{ asset ('js/custom.js') }}"></script>